#!/bin/bash
#SBATCH --quotatype spot
#SBATCH --partition optimal
#SBATCH --gres gpu:4
#SBATCH -o phoenix-slurm-%j.out
# args: --quotatype=spot
# args: -p
# args: optimal
# args: --gres=gpu:4
# args: python
# args: run.py
# args: configs/eval_customize.py
argv=()
while read -r line; do
    if [[ $line == "# args: "* ]]; then
        argv[${#argv[*]}]="${line:8}"
    fi
done < $0

srun "${argv[@]}"
