#!/bin/bash
#SBATCH --partition optimal
#SBATCH --gres gpu:1
#SBATCH -o phoenix-slurm-%j.out
# args: -p
# args: optimal
# args: --gres=gpu:1
# args: python
# args: run.py
# args: configs/eval_customize_api.py
argv=()
while read -r line; do
    if [[ $line == "# args: "* ]]; then
        argv[${#argv[*]}]="${line:8}"
    fi
done < $0

srun "${argv[@]}"
